### ISSUE TITLE
Unable to use S3

### ISSUE THREAD

**Issue by renege** [mostafaznv/larupload#21]
Configured `config/laraupload.php` to `'disk' => 's3',` but not working. @mostafaznv

**Comment by mostafaznv** [comment]
Hi @renege,
Could you please provide more details about the issue?

**Comment by renege** [comment]
File not found after uploading and not downloadable..:

![Scherm­afbeelding 2023-11-05 om 17 33 16](https://github.com/mostafaznv/larupload/assets/2900069/21c93825-d05c-458e-af8a-68a1c81f9df7)


Can you give an example of how to use it with S3?

P.S. Using Vapor

**Comment by mostafaznv** [comment]
Right now, I'm using this with MinIO, which is an S3-compatible service, and this is my configuration:


```php
# config/larupload.php
return [
    'disk' => 'uploads',
];
```

```php
# config/filesystems.php
return [
    'disks' => [
        'uploads' => [
            'driver'                  => 's3',
            'key'                     => env('MINIO_KEY'),
            'secret'                  => env('MINIO_SECRET'),
            'region'                  => env('MINIO_REGION'),
            'bucket'                  => 'uploads',
            'endpoint'                => env('MINIO_ENDPOINT'),
            'visibility'              => 'public',
            'url'                     => env('MINIO_URL') . '/uploads',
            'use_path_style_endpoint' => env('MINIO_USE_PATH_STYLE_ENDPOINT', true),
            'throw'                   => false,
        ]
    ],
];
```
It works great on Nova. However, because I'm living in Iran, I can't purchase anything in Vapor or AWS, unfortunately. 
There might be some differences in using it there.

Please consider these steps:
- Try using the package with a local file driver and check if everything is working correctly.
- Log in to your S3 service manually and verify whether any files are present or not.
- Double-check your filesystem configuration to ensure that it generates the correct URL for the files.


Let me know the results, and if you need further assistance, I'll be happy to help you.
