### ISSUE TITLE
Hashids is now Sqids

### ISSUE THREAD

**Issue by jorgelloret** [mostafaznv/larupload#24]
As indicated at https://github.com/hashids, the project has been renamed Sqids.

**Comment by mostafaznv** [comment]
As I see, it seems [`hashids/hashids`](https://github.com/vinkla/hashids) is still alive.
I've checked https://github.com/sqids/sqids-php as well and as it is on beta versions (0.4.1) I think it's not a good decsition to migrate to sqids for now.

Is there any other reason to migrate to sqids?

Hi @jorgelloret,
Thanks for the report.

Upon review, it appears that [`hashids/hashids`](https://github.com/vinkla/hashids) is still active.
I've also looked into [`sqids/sqids-php`](https://github.com/sqids/sqids-php), but since it's currently in beta versions (0.4.1), I believe it's not advisable to migrate to `sqids` at the moment.

Do you have any other reasons for considering a migration to `sqids`?
